import 'package:news_app/core/constants/constants.dart';
import 'package:news_app/features/daily_news/data/models/article_model.dart';
import 'package:retrofit/retrofit.dart';
import 'package:dio/dio.dart';

// This tells Retrofit to generate the implementation file (news_api_service.g.dart) by running `flutter pub run build_runner build`
part 'news_api_service.g.dart';

// Uses Retrofit's @RestApi annotation to define an API service.
// Sets the baseUrl to newsAPIBaseURL (e.g., "https://newsapi.org/v2").
@RestApi(baseUrl: newsAPIBaseURL)
abstract class NewsApiService {
  // This automatically creates an instance of _NewsApiService (generated by Retrofit)
  factory NewsApiService(Dio dio) = _NewsApiService;

  // @GET('/top-headlines') → Sends a GET request to https://newsapi.org/v2/top-headlines
  @GET('/top-headlines')
  Future<HttpResponse<List<ArticleModel>>> getNewsArticles({
    // Uses @Query() parameters to pass API key, country, and category
    @Query('apiKey') String? apiKey,
    @Query('country') String? country,
    @Query('category') String? category,
  });
}
